

// Revenue: The total revenue generated by the gym over a given time period.(admin)
// payment Method: The method of payment, such as credit card, or cheque.
// checkbalance();//how much paid and how much left(bool variable)
// paysalary();//wallet(float );(salary given to trainer from file of admin)
// wallet is an extra attribute custom to gym (Admin->>>trainer->>client) through id
// equipment ki prices bhi deduct hongi na
// Transaction ID: A unique identifier for each transaction.
// Transaction Date: The date on which the transaction occurred.
// Transaction Type: The type of transaction, such as membership fee, equipment purchase, or personal training session.
// Transaction Amount: The amount of money involved in the transaction.
// create a class and compose its object in all 3 classes
// Late Payment Fee: The fee charged for late payments(time library)

// menu();
// Revenue: The total revenue generated by the gym over a given time period.(admin)
// payment Method: The method of payment, such as credit card, or cheque.
// checkbalance();//how much paid and how much left(bool variable)
// paysalary();//wallet(float );(salary given to trainer from file of admin)
// wallet is an extra attribute custom to gym (Admin->>>trainer->>client) through id
// equipment ki prices bhi deduct hongi na
// Transaction ID: A unique identifier for each transaction.
// Transaction Date: The date on which the transaction occurred.
// Transaction Type: The type of transaction, such as membership fee, equipment purchase, or personal training session.
// Transaction Amount: The amount of money involved in the transaction.
// create a class and compose its object in all 3 classes
// Late Payment Fee: The fee charged for late payments(time library)
